#FROM --platform=linux/arm64/v8 eclipse-temurin:17-jdk AS build
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /workspace/app
# Copy Maven wrapper and pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
# Install dependencies
RUN ./mvnw dependency:go-offline
# Copy source files
COPY src src
# Package the application, skipping tests, and verify the JAR file is in target/
RUN ./mvnw package -DskipTests
# Stage 2: Setup the runtime environment
#FROM --platform=linux/arm64/v8 eclipse-temurin:17-jdk
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
# Copy the built artifact from the build stage into the /app directory
COPY --from=build /workspace/app/target/klantenportaal-0.0.1-SNAPSHOT.jar .
# Define the ENTRYPOINT for running the jar
ENTRYPOINT ["java", "-jar", "klantenportaal-0.0.1-SNAPSHOT.jar"]

# Expose the port the application runs on
EXPOSE 8080
